import { generateRssFeed } from "feedsmith";
import type { CategorySummary } from "./summarize.ts";
import type { CategorizedItems } from "./categorize.ts";
import type { FeedItem } from "./rss.ts";

export type OutputFormat = "markdown" | "rss" | "all";

function formatDate(date: Date): string {
  return date.toISOString().split("T")[0]!;
}

function formatDisplayDate(date: Date): string {
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function getSafeCategoryName(category: string): string {
  return category.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

function generateMarkdownContent(
  summary: CategorySummary,
  date: Date
): string {
  const lines: string[] = [];

  lines.push(`# ${summary.category} Summary - ${formatDisplayDate(date)}`);
  lines.push("");

  // Overview section
  lines.push("## Overview");
  lines.push("");
  lines.push(summary.overview);
  lines.push("");

  // Highlights section
  if (summary.highlights.length > 0) {
    lines.push("## Key Highlights");
    lines.push("");
    for (const highlight of summary.highlights) {
      lines.push(`- ${highlight}`);
    }
    lines.push("");
  }

  // All articles table
  if (summary.items.length > 0) {
    lines.push("## All Articles");
    lines.push("");
    lines.push("| Title | Source | Date |");
    lines.push("|-------|--------|------|");

    for (const item of summary.items) {
      const title = item.link
        ? `[${item.title}](${item.link})`
        : item.title;
      const itemDate = item.pubDate
        ? item.pubDate.toLocaleDateString()
        : "Unknown";
      lines.push(`| ${title} | ${item.feedTitle} | ${itemDate} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by smart-rss on ${formatDisplayDate(new Date())}*`);

  return lines.join("\n");
}

function generateMarkdownWithoutSummary(
  category: string,
  items: FeedItem[],
  date: Date
): string {
  const lines: string[] = [];

  lines.push(`# ${category} - ${formatDisplayDate(date)}`);
  lines.push("");

  if (items.length > 0) {
    lines.push("## Articles");
    lines.push("");
    lines.push("| Title | Source | Date |");
    lines.push("|-------|--------|------|");

    for (const item of items) {
      const title = item.link
        ? `[${item.title}](${item.link})`
        : item.title;
      const itemDate = item.pubDate
        ? item.pubDate.toLocaleDateString()
        : "Unknown";
      lines.push(`| ${title} | ${item.feedTitle} | ${itemDate} |`);
    }
    lines.push("");
  } else {
    lines.push("No articles found.");
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by smart-rss on ${formatDisplayDate(new Date())}*`);

  return lines.join("\n");
}

function generateRssContent(summary: CategorySummary, date: Date): string {
  const feedItems = summary.items.slice(0, 100).map((item) => ({
    title: item.title,
    link: item.link || undefined,
    description: item.description || undefined,
    pubDate: item.pubDate || undefined,
    guid: item.link ? { value: item.link } : { value: `${item.feedTitle}-${item.title}` },
  }));

  const rss = generateRssFeed(
    {
      title: `${summary.category} Summary - ${formatDate(date)}`,
      link: "",
      description: summary.overview,
      items: feedItems,
      pubDate: date,
      lastBuildDate: new Date(),
    },
    { lenient: true }
  );

  return rss;
}

export async function writeMarkdownOutput(
  summaries: CategorySummary[],
  outputDir: string,
  date: Date
): Promise<string[]> {
  const summariesDir = `${outputDir}/summaries`;
  const dateStr = formatDate(date);
  const writtenFiles: string[] = [];

  for (const summary of summaries) {
    const safeName = getSafeCategoryName(summary.category);
    const filePath = `${summariesDir}/${dateStr}-${safeName}.md`;
    const content = generateMarkdownContent(summary, date);

    await Bun.write(filePath, content);
    writtenFiles.push(filePath);
  }

  return writtenFiles;
}

export async function writeMarkdownWithoutSummary(
  categorized: CategorizedItems,
  outputDir: string,
  date: Date
): Promise<string[]> {
  const summariesDir = `${outputDir}/summaries`;
  const dateStr = formatDate(date);
  const writtenFiles: string[] = [];

  for (const [category, items] of Object.entries(categorized)) {
    const safeName = getSafeCategoryName(category);
    const filePath = `${summariesDir}/${dateStr}-${safeName}.md`;
    const content = generateMarkdownWithoutSummary(category, items, date);

    await Bun.write(filePath, content);
    writtenFiles.push(filePath);
  }

  return writtenFiles;
}

export async function writeRssOutput(
  summaries: CategorySummary[],
  outputDir: string,
  date: Date
): Promise<string[]> {
  const feedsDir = `${outputDir}/feeds`;
  const writtenFiles: string[] = [];

  for (const summary of summaries) {
    const safeName = getSafeCategoryName(summary.category);
    const filePath = `${feedsDir}/${safeName}.xml`;
    const content = generateRssContent(summary, date);

    await Bun.write(filePath, content);
    writtenFiles.push(filePath);
  }

  return writtenFiles;
}

export async function writeRssWithoutSummary(
  categorized: CategorizedItems,
  outputDir: string,
  date: Date
): Promise<string[]> {
  const feedsDir = `${outputDir}/feeds`;
  const writtenFiles: string[] = [];

  for (const [category, items] of Object.entries(categorized)) {
    const safeName = getSafeCategoryName(category);
    const filePath = `${feedsDir}/${safeName}.xml`;

    const feedItems = items.slice(0, 100).map((item) => ({
      title: item.title,
      link: item.link || undefined,
      description: item.description || undefined,
      pubDate: item.pubDate || undefined,
      guid: item.link ? { value: item.link } : { value: `${item.feedTitle}-${item.title}` },
    }));

    const rss = generateRssFeed(
      {
        title: `${category} - ${formatDate(date)}`,
        link: "",
        description: `RSS feed for ${category}`,
        items: feedItems,
        pubDate: date,
        lastBuildDate: new Date(),
      },
      { lenient: true }
    );

    await Bun.write(filePath, rss);
    writtenFiles.push(filePath);
  }

  return writtenFiles;
}

export async function ensureOutputDirectories(outputDir: string): Promise<void> {
  await Bun.write(`${outputDir}/raw/.gitkeep`, "");
  await Bun.write(`${outputDir}/summaries/.gitkeep`, "");
  await Bun.write(`${outputDir}/feeds/.gitkeep`, "");
}
